FROM cn007b/python:3.7

MAINTAINER V. Kovpak <cn007b@gmail.com>

RUN pip3 install numpy matplotlib

# pytorch
RUN pip3 install torch
# torchvision

# tensorflow
RUN pip3 install virtualenv tensorflow tensorboard

# kubeflow
RUN pip3 install kubernetes kfp
